/**
 * Created by antianlu on 2017/5/4.
 */

export const APLLYCARD_GET_PAGEINFO = 'APLLYCARD_GET_PAGEINFO'
export const APPLYCARD_GET_SUCCESS = 'APPLYCARD_GET_SUCCESS'
export const APPLYCARD_GET_ORDER = 'APPLYCARD_GET_ORDER'
export const APPLYCARD_SHARE = 'APPLYCARD_SHARE'
export const APPLYCARD_GET_MYORDER = 'APPLYCARD_GET_MYORDER'
